

spring:
  config:
    import: optional:configserver:http://localhost:8888/
  application:
    name: service-discovery
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # not allow to register to himself
    fetch-registry: false # not fetch from registry
    service-url:
      defaultZone: http://${eureka.instance.hostname}/${server.port}/eureka

server:
  port: 8761
